name: cs-linker
services:
  cs_links_db:
    image: mariadb:11.8-ubi9
    environment:
      MYSQL_ROOT_PASSWORD: devpw
      MYSQL_DATABASE: cslinks
    volumes:
      - cs-links-db:/var/lib/mysql
    ports:
      - "3307:3306"
         
volumes:
  cs-links-db:
    driver: local
