version: "3.7"

services:
  cs_links_db:
    image: mariadb:10.6.3-focal
    environment:
      MYSQL_ROOT_PASSWORD: devpw
      MYSQL_DATABASE: cslinks
    volumes:
      - cs-links-db:/var/lib/mysql
    ports:
      - "3307:3306"
         
volumes:
  cs-links-db:
    driver: local
